name: flo-app
services:
  postgres:
    image: postgres
    env_file: postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d flo'" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  flo-api:
    image: ghcr.io/zp1ke/flo-api:latest
    env_file: api.env
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/flo
      WEB_BASE_URL: http://flo-web
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  flo-web:
    image: ghcr.io/zp1ke/flo-app:latest
    environment:
      VITE_API_BASE_URL: http://flo-api:8080/api/v1
      NODE_ENV: production
    ports:
      - 80:80
    depends_on:
      flo-api:
        condition: service_healthy
