spring:
  application:
    timezone: ${TIMEZONE:UTC}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  devtools:
    addProperties: false
  jpa:
    showSql: ${DATABASE_SHOW_SQL:false}
    properties:
      hibernate:
        formatSql: true
        showSql: ${DATABASE_SHOW_SQL:false}

jwt:
  secret: ${JWT_SECRET}
  expirationInHours: ${JWT_EXPIRATION_MINUTES:720}

server:
  port: 8080

mail:
  host: ${MAIL_HOST:}
  port: ${MAIL_PORT:0}
  handler: ${MAIL_HANDLER:SMTP}
  useTLS: ${MAIL_USE_TLS:false}
  useSSL: ${MAIL_USE_SSL:false}
  username: ${MAIL_USER:}
  password: ${MAIL_PASSWORD:}
  senderEmail: ${MAIL_FROM:}
  sandbox: ${MAIL_SANDBOX:false}

storage:
  endpoint: ${STORAGE_HOST:}
  accessKey: ${STORAGE_ACCESS_KEY}
  secretKey: ${STORAGE_SECRET_KEY}
  bucket: ${STORAGE_BUCKET}

jobrunr:
  dashboard:
    port: 8081

web:
  baseUrl: ${WEB_BASE_URL}
  logoImageUrl: ${WEB_BASE_URL}/images/logo-light.png
