spring:
  application:
    name: flo-api
  datasource:
    driverClassName: org.postgresql.Driver
  jackson:
    defaultPropertyInclusion: NON_NULL
    serialization:
      failOnEmptyBeans: false
  jpa:
    hibernate:
      ddlAuto: validate
      formatSql: true
    openInView: false
    showSql: true
    properties:
      hibernate:
        formatSql: true
        showSql: true
  liquibase:
    changeLog: classpath:db/changelog.yml
    enabled: true
    liquibaseSchema: liquibase
  output:
    ansi:
      enabled: always

springdoc:
  apiDocs:
    path: /api/v1/docs
  swaggerUi:
    path: /api/v1/docs/ui.html

management:
  endpoints:
    web:
      exposure:
        include: info,health

org.jobrunr:
  background-job-server:
    enabled: true
  dashboard:
    enabled: true
  database:
    table-prefix: jobrunr.
    type: sql
  jobs:
    metrics:
      enabled: true

logging:
  level:
    root: INFO
    com.zp1ke.flo: DEBUG
