spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expirationInHours: ${JWT_EXPIRATION_MINUTES:720}

server:
  port: 8080

org.jobrunr:
  dashboard:
    port: 8081
