services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flo
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d flo'" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  maildev:
    image: maildev/maildev
    environment:
      MAILDEV_MAIL_DIRECTORY: /home/maildev
    ports:
      - 1080:1080
      - 1025:1025
    volumes:
      - ./data/maildev:/home/maildev
