name: flo-dev
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flo
    ports:
      - 5432:5432
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    # environment:
    #   MAILDEV_MAIL_DIRECTORY: /home/maildev
    ports:
      - 1080:1080
      - 1025:1025
    # volumes:
    #   - ./data/maildev:/home/maildev

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: flo-access-key
      MINIO_ROOT_PASSWORD: flo-secret-key
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
