name: Backend Test

on:
  workflow_dispatch:
  push:
    paths:
      - backend/**

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        working-directory: ./backend
        run: ./gradlew clean test
