name: Build & Release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}-api
  APP_IMAGE_NAME: ${{ github.repository }}-app

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Backend Version from gradle.properties
        working-directory: ./backend
        run: |
          version=$(grep '^version=' gradle.properties | cut -d '=' -f 2 | tr -d '\r')
          echo "API_VERSION=$version" >> $GITHUB_ENV

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build API JAR
        working-directory: ./backend
        run: ./gradlew flo-api:bootJar

      - name: Extract App Version from package.json
        working-directory: ./front
        run: |
          version=$(grep '^  "version": ' package.json | cut -d '"' -f 4)
          echo "APP_VERSION=$version" >> $GITHUB_ENV

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: LogIn to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API Docker image
        id: push-api
        uses: docker/build-push-action@v6
        with:
          context: "./backend/flo-api"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ env.API_VERSION }}

      - name: Build and push APP Docker image
        id: push-app
        uses: docker/build-push-action@v6
        with:
          context: "./front"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ env.APP_VERSION }}

      - name: Generate API artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
          subject-digest: ${{ steps.push-api.outputs.digest }}
          push-to-registry: true

      - name: Generate APP artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}
          subject-digest: ${{ steps.push-app.outputs.digest }}
          push-to-registry: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: |
            backend/flo-api/build/libs/flo-api-*.jar
            front/build/client/*

      - name: Check if Version Tag exists
        run: |
          if git rev-parse "v${{ env.APP_VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Modify Version Tag if exists
        if: env.TAG_EXISTS == 'true'
        run: |
          new_version="${{ env.APP_VERSION }}-build-${{ github.run_number }}"
          echo "APP_VERSION=$new_version" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            backend/flo-api/build/libs/flo-api-*.jar
            front/build/client/*
          tag: ${{ env.APP_VERSION }}
